dist: xenial
language: node_js
node_js:
  - 8.11.4
install:
  - npm install
before_script:
  - export PATH="$PATH:./node_modules/.bin"
  - truffle version
  - truffle install
script:
  - npm run lint
  - travis_wait 30 npm run test-cov
after_script:
  - echo Build completed on `date`
  - npm run coveralls-collect
branches:
  only:
  - master
